services:
  db:
    image: mysql:latest
    container_name: mysql_demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_injection_demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi_demo
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: demo
      DB_PASSWORD: demo123
      DB_NAME: sql_injection_demo

volumes:
  mysql_data: {}